package io.github.soclear.oneuix.ui.theme

import androidx.compose.ui.graphics.Color

// アプリアイコンのシアン（#0891B2）を種にした Material 3 のトーナルパレット。
// Dynamic Color が使えない場合のみ使われる。

val LightPrimary = Color(0xFF006878)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFA2EEFF)
val LightOnPrimaryContainer = Color(0xFF001F26)
val LightSecondary = Color(0xFF4A6268)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCDE7ED)
val LightOnSecondaryContainer = Color(0xFF051F24)
val LightTertiary = Color(0xFF525E7D)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDAE2FF)
val LightOnTertiaryContainer = Color(0xFF0E1B37)
val LightBackground = Color(0xFFFAFDFE)
val LightOnBackground = Color(0xFF191C1D)
val LightSurface = Color(0xFFFAFDFE)
val LightOnSurface = Color(0xFF191C1D)
val LightSurfaceVariant = Color(0xFFDBE4E6)
val LightOnSurfaceVariant = Color(0xFF3F484A)
val LightOutline = Color(0xFF6F797A)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF4F7F8)
val LightSurfaceContainer = Color(0xFFEEF1F2)
val LightSurfaceContainerHigh = Color(0xFFE8EBEC)
val LightSurfaceContainerHighest = Color(0xFFE2E5E6)

val DarkPrimary = Color(0xFF52D7F0)
val DarkOnPrimary = Color(0xFF00363F)
val DarkPrimaryContainer = Color(0xFF004E5A)
val DarkOnPrimaryContainer = Color(0xFFA2EEFF)
val DarkSecondary = Color(0xFFB1CBD1)
val DarkOnSecondary = Color(0xFF1C3439)
val DarkSecondaryContainer = Color(0xFF334B50)
val DarkOnSecondaryContainer = Color(0xFFCDE7ED)
val DarkTertiary = Color(0xFFBAC6EA)
val DarkOnTertiary = Color(0xFF24304D)
val DarkTertiaryContainer = Color(0xFF3B4664)
val DarkOnTertiaryContainer = Color(0xFFDAE2FF)
val DarkBackground = Color(0xFF191C1D)
val DarkOnBackground = Color(0xFFE1E3E3)
val DarkSurface = Color(0xFF191C1D)
val DarkOnSurface = Color(0xFFE1E3E3)
val DarkSurfaceVariant = Color(0xFF3F484A)
val DarkOnSurfaceVariant = Color(0xFFBFC8CA)
val DarkOutline = Color(0xFF899294)
val DarkSurfaceContainerLowest = Color(0xFF0C0F10)
val DarkSurfaceContainerLow = Color(0xFF191C1D)
val DarkSurfaceContainer = Color(0xFF1D2021)
val DarkSurfaceContainerHigh = Color(0xFF272B2B)
val DarkSurfaceContainerHighest = Color(0xFF323536)
